### ISSUE TITLE
Apply a more appropriate naming convention across the projects

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.SpecFlow.Extensions#85]
I'm thinking of renaming the existing projects in the solution as follows:

- `Corvus.SpecFlow.Extensions` -> `Corvus.Testing.XXX.SpecFlow`, where XXX is a specific bit of functionality - for example, the Azure Functions bits from that project -> `Corvus.Testing.AzureFunctions.SpecFlow`
- `Corvus.SpecFlow.Extensions.Demo` -> `Corvus.Testing.AzureFunctions.SpecFlow.Demo`
- `Corvus.SpecFlow.Extensions.DemoFunction` -> `Corvus.Testing.AzureFunctions.DemoFunction`.

We already have our first two `Corvus.Testing...` projects in the solution thanks to #83. This change will bring the remaining projects in line with them.

**Comment by mwadams** [comment]
Agreed. And we need to rename this repo to Corvus.Testing.

We then need to add "deprecated redirects" to NUGET so that people get the new versions of the newly named assemblies/packages.

And then update all of the testing packages in the rest of our IP so that they pick up the new specs packages *or we will forget*.

We don't need to produce releases for everything else, though, as it is "specs only".
